### ISSUE TITLE
I hope there is a website to demo this project

### ISSUE THREAD

**Issue by franklinqin0** [vuepress/awesome-vuepress#149]
While VuePress is built for documentations and this project serves as a documentation for VuePress, why shouldn't we build a website to demo various plugins and themes, rather than clicking into each one and find a demo?

Simply put, turn README.md to a colorful site.

**Comment by billyyyyy3320** [comment]
Currently, you can check out https://z3by.github.io/vuepress-tools/

**Comment by franklinqin0** [comment]
Thanks! However, I see that there is a bug with the images not showing up if image path is relative instead of absolute.

**Comment by franklinqin0** [comment]
And I don't see my favorite theme [reco](https://vuepress-theme-reco.recoluan.com/) tho...

**Comment by ulivz** [comment]
@franklinqin0 feel free to submit a pull request to add it
